version: '3'
volumes:
  avd_volume:
    driver: local

services:
  avd-builder:
    container_name: avd_builder
    build: '../docker/avd/'
    environment:
      - REPO_AVD_DATA=https://github.com/titom73/avd-for-compose-kubernetes-demo.git
      - ANSIBLE_PLAYBOOK=dc1-fabric-deploy-cvp.yml
      - ANSIBLE_TAGS=build
    volumes:
      - avd_volume:/web
  avd-web:
    container_name: avd_web
    image: "nginx"
    ports:
      - "8080:80"
    volumes:
      - avd_volume:/usr/share/nginx/html/
